server:
  port: 8080

logging:
  level:
    root: info
#
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      console.settings.trace: true
#      spring.h2.console.settings.web-allow-others: false
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    platform: h2
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        globally_quoted_identifiers: false
#        ddl-auto: create
#        show_sql: true
#        format_sql: true
#
